### ISSUE TITLE
Unkown template in test definitions breaks PR-CI

### ISSUE THREAD

**Issue by netoarmando** [freeipa/freeipa-pr-ci#257]
PR-CI breaks if some job passes a template that is not defined in the build job. This issue was observed in production, not yet reproduced in a development environment.

```
jobs:
  fedora-29/build:
    requires: []
    priority: 100
    job:
      class: Build
      args:
        git_repo: '{git_repo}'
        git_refspec: '{git_refspec}'
        template: &ci-master-f29 <--------------------
          name: freeipa/ci-master-f29
          version: 0.2.0
        timeout: 1800
        topology: *build

  fedora-29/temp_commit:
    requires: [fedora-29/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-29/build_url}'
        test_suite: test_integration/test_REPLACEME.py
        template: *ci-master-frawhide <--------------------
        timeout: 3600
        topology: *master_1repl_1client
```
