### ISSUE TITLE
prci crashes with RunADTests and does not report any issue

### ISSUE THREAD

**Issue by flo-renaud** [freeipa/freeipa-pr-ci#306]
PRCI is crashing when the following test definition is used:
```
  fedora-30/test_smb:
    requires: [fedora-30/build]
    priority: 50
    job:
      class: RunADTests
      args:
        build_url: '{fedora-30/build_url}'
        test_suite: test_integration/test_smb.py
        template: *ci-master-f30
        timeout: 4800
        topology: *ad_master_2client
```

The journal logs for PRCI logs show the following:
```
bash[31394]: Traceback (most recent call last):
bash[31394]:   File "/root/freeipa-pr-ci/github/prci.py", line 316, in <module>
bash[31394]:     main()
bash[31394]:   File "/root/freeipa-pr-ci/github/prci.py", line 291, in main
bash[31394]:     for task in process_pull_request(world, pull_request, repo_url):
bash[31394]:   File "/root/freeipa-pr-ci/github/prci.py", line 124, in process_pull_request
bash[31394]:     pull_request.author, repository_url, task_data, JobDispatcher
bash[31394]:   File "/root/freeipa-pr-ci/github/internals/entities.py", line 593, in __init__
bash[31394]:     "git_refspec": self.ref_spec
bash[31394]:   File "/root/freeipa-pr-ci/github/internals/entities.py", line 809, in __init__
bash[31394]:     self.task_class = getattr(tasks, job_data["class"])
bash[31394]: AttributeError: module 'tasks.tasks' has no attribute 'RunADtests'
systemd[1]: prci.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: prci.service: Failed with result 'exit-code'.
```

So we have 2 issues:
- using RunADTests makes PRCI crash
- when PRCI crashes, the PR is showing as green (see for instance PR [3576](https://github.com/freeipa/freeipa/pull/3576)) and we don't detect that some of the tests were not triggered.
