### ISSUE TITLE
RunADTests failing with the latest update

### ISSUE THREAD

**Issue by flo-renaud** [freeipa/freeipa-pr-ci#509]
Any job using the RunADTests description is now failing in PRCI.

This happens because the variables set in templates/ad.vars.yml are missing the variable trusted_domain.
The result is that the jinja template in master/ansible/roles/machine/provision/templates/ipa-test-config.yaml
is transformed into a config file containing an empty domain definition for the trusted domain:
```
- hosts:
  name: trustedipa.test
  type: TRUSTED_IPA

- name: ad.test
  type: AD
  hosts:
    - external_hostname: ad-root.ad.test
      ip: 192.168.121.43
      name: ad-root.ad.test
      role: ad
      username: Administrator
      password: Secret123
```
and this empty domain is not recognized.

Example of failing run in http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/2444fbce-6c51-11ef-bea6-fa163ea9ad15/
